apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongo-secret
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{ if .Values.mxcore.externalMongoSecret.enabled -}}
    host: {{ .Values.mxcore.externalMongo.host | b64enc }}
    port: {{ .Values.mxcore.externalMongo.port | b64enc }}
    user: {{ .Values.mxcore.externalMongo.user | b64enc }}
    password: {{ .Values.mxcore.externalMongo.password | b64enc }}
    database: {{ .Values.mxcore.externalMongo.database | b64enc }}
  {{- else -}}

  {{- end }}
